### ISSUE TITLE
BUG: Missing fields

### ISSUE THREAD

**Issue by lucasrodes** [india-covid19vaccine/india-covid19vaccine.github.io#5]
Hi,
I have noticed that the last data update contains empty fields for all columns but `total_vaccinated`

See last row [here](https://github.com/india-covid19vaccine/india-covid19vaccine.github.io/blob/main/csv/AN.csv) for an example.

**Comment by sanyam-git** [comment]
Thanks for informing @lucasrodes. It was a human error. Fixed it in the latest update.
